export const projectList = [
  {
    projectId: "123",
    title: "Add Logout Button",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "456",
    title: "Add Profile Pic Upload",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "789",
    title: "Update Documentation",
    phase: "In Review",
    updated: "May 22, 2023",
  },
  {
    projectId: "abc",
    title: "Organize Quarterly Profit Sharing Meeting",
    phase: "In Progress",
    updated: "May 5, 2023",
  },
  {
    projectId: "123",
    title: "Add Logout Button",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "456",
    title: "Add Profile Pic Upload",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "789",
    title: "Update Documentation",
    phase: "In Review",
    updated: "May 22, 2023",
  },
  {
    projectId: "abc",
    title: "Organize Quarterly Profit Sharing Meeting",
    phase: "In Progress",
    updated: "May 5, 2023",
  },
  {
    projectId: "123",
    title: "Add Logout Button",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "456",
    title: "Add Profile Pic Upload",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "789",
    title: "Update Documentation",
    phase: "In Review",
    updated: "May 22, 2023",
  },
  {
    projectId: "abc",
    title: "Organize Quarterly Profit Sharing Meeting",
    phase: "In Progress",
    updated: "May 5, 2023",
  },
  {
    projectId: "123",
    title: "Add Logout Button",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "456",
    title: "Add Profile Pic Upload",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "789",
    title: "Update Documentation",
    phase: "In Review",
    updated: "May 22, 2023",
  },
  {
    projectId: "abc",
    title: "Organize Quarterly Profit Sharing Meeting",
    phase: "In Progress",
    updated: "May 5, 2023",
  },
  {
    projectId: "123",
    title: "Add Logout Button",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "456",
    title: "Add Profile Pic Upload",
    phase: "Not Started",
    updated: "Nov 5, 1605",
  },
  {
    projectId: "789",
    title: "Update Documentation",
    phase: "In Review",
    updated: "May 22, 2023",
  },
  {
    projectId: "abc",
    title: "Organize Quarterly Profit Sharing Meeting",
    phase: "In Progress",
    updated: "May 5, 2023",
  },
];
